version: '3.8'

services:
  mojila-signal:
    build: .
    container_name: mojila-signal-services
    ports:
      - "5000:5000"
    volumes:
      - ./config.py:/app/config.py:ro
      - ./my_portfolio.txt:/app/my_portfolio.txt:ro
      - ./telegram_config.json:/app/telegram_config.json:ro
      - ./scan_list.txt:/app/scan_list.txt:ro
      - ./signals.db:/app/signals.db
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
      - FLASK_ENV=production
      - FLASK_DEBUG=false
    restart: unless-stopped
    command: ["./start-services.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Web interface service
  mojila-web:
    build: .
    container_name: mojila-signal-web
    command: ["python", "app.py"]
    volumes:
      - ./signals.db:/app/signals.db
      - ./my_portfolio.txt:/app/my_portfolio.txt:ro
      - ./scan_list.txt:/app/scan_list.txt:ro
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=production
      - TZ=UTC
    ports:
      - "8080:5000"
    restart: unless-stopped
    depends_on:
      - mojila-signal
    profiles:
      - web

volumes:
  signal_data:
    driver: local